# Generated by Django 2.0.6 on 2018-08-08 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_desc', models.CharField(max_length=10)),
                ('pic_name', models.CharField(max_length=250)),
                ('pic_publicity', models.CharField(choices=[('0', 'Just Me'), ('1', 'Friends'), ('2', 'Everyone')], max_length=1)),
                ('picture', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_level', models.CharField(choices=[('0', 'Just Me'), ('1', 'Friends'), ('2', 'Everyone')], max_length=1)),
                ('bio', models.CharField(max_length=500)),
                ('profile_picture', models.FileField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pic',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Prof'),
        ),
    ]
